name: expense_track
version: 1.0.0+1
publish_to: none
description: App for tracking money spent
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^1.0.8
  http: ^1.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
#  assets:
#    - /assets/profile.jpg
